name: cicd-pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./gallery_am_fluss
          file: ./gallery_am_fluss/Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: |
            linusbittner/gallery-am-fluss:latest
            linusbittner/gallery-am-fluss:${{ github.sha }}

      - name: Discord Notification (success)
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content": "✅ Docker Build sucessfull!\nEvent: ${{ github.event_name }}\nRepo: ${{ github.repository }}\nCommit: ${{ github.sha }}"}' \
               ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Discord Notification (failure)
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content": "❌ Docker Build/Push failed!\nEvent: ${{ github.event_name }}\nRepo: ${{ github.repository }}\nCommit: ${{ github.sha }}"}' \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
