name: cicd-pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image (no push on PR)
        uses: docker/build-push-action@v5
        with:
          context: ./gallery_am_fluss
          file: ./gallery_am_fluss/Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gallery-am-fluss:latest

      - name: Discord Notification (success)
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content": "✅ Docker Build erfolgreich! \nEvent: ${{ github.event_name }} \nRepo: ${{ github.repository }} \nCommit: ${{ github.sha }}"}' \
               ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Discord Notification (failure)
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content": "❌ Docker Build/Push fehlgeschlagen! \nEvent: ${{ github.event_name }} \nRepo: ${{ github.repository }} \nCommit: ${{ github.sha }}"}' \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
