name: Deploy Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Run Docker Compose File
      run: docker compose -f gallery_am_fluss/docker-compose.yml up -d

    - name: Upload Docker Compose Logs
      uses: actions/upload-artifact@v3
      with:
        name: docker-compose-logs
        path: docker-compose.log
